apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: voting-app
  labels:
    app: voting-app
    tier: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: voting-app
    tier: database
